services:
#Backend SafeTrade (NestJS + Node.js)
  backend:
    image: safetrade-backend:latest
    container_name: safetrade-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}

      # Cloudinary
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      # Email
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SENDER_EMAIL: ${SENDER_EMAIL}

      NODE_ENV: production
      PORT: 3000

    networks:
      - safetrade-network
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:3000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Frontend SafeTrade (React + Vite + Nginx)
  frontend:
    image: safetrade-frontend:latest
    container_name: safetrade-frontend

    ports:
      - "5173:80"

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - safetrade-network
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

# Red del proyecto
networks:
  safetrade-network:
    driver: bridge
